### ISSUE TITLE
[Bug]: The new Ender Pearls can't craft into Eyes of Ender

### ISSUE THREAD

**Issue by SirWoofie** [bonsaistudi0s/EndermanOverhaul#40] opened 2024-02-06 03:41 UTC
### Bug Description

There are new Ender Pearl variants added by this mod, but when attempting to use them to craft an Eye of Ender, there is no recipe. Seeing as the new enderman variants replace many existing endermen in many locations, it becomes significantly harder to obtain a normal Ender Pearl for the various recipes that are not 1-1 compatible with the new Ender Pearl variants.

### How to Reproduce?

1. Obtain one of the new Ender Pearl variants and some blaze powder.
2. Craft 1 of the Ender Pearl variants with one blaze powder.
3. No recipe for Eye of Ender.

### Expected Behavior

When using any kind of Ender Pearl dropped by an enderman, it should be craftable in any recipe that uses a vanilla Ender Pearl, including when crafting a vanilla Eye of Ender.

### Version

1.0.4

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Logs or additional context

Played in a modified version of the All The Mods 9 version 0.2.41 modpack.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment] 2024-02-29 00:17
Duplicate of #32

**Closed as not planned by AlexNijjar** 2024-02-29 00:17 UTC
Labels: bug, duplicate
